import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { ProductList } from '../components/ProductList';
import {Header} from 'https://ui-l.vercel.app/Header.mjs'
import {Footer} from 'https://ui-l.vercel.app/Footer.mjs'
import { useState, useEffect } from 'react';
import App from './_app';

export const getServerSideProps = async () => {
  const res = await fetch('https://dummyjson.com/products')
  const {products} = await res.json()
  return { props: { products } }
}

export default function Home({products}) {
  const [count, setCount] = useState(0)
  const [hydrated, setHydrated] = useState(false);
    
  useEffect(() => {
        setHydrated(true);
    }, []);

    if (!hydrated) {
        // Returns null on first render, so the client and server match
        return null;
    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Header title='Home Page' count={count}/>
        <ProductList products={products} setCount={setCount}/>
        <div>Hosted at : https://next-ssr-lac-chi.vercel.app </div>
        <App Component={Footer} pageProps={{className: styles.footer}}/>
      </main>
    </>
  )
}
