import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { ProductList } from '../components/ProductList';
import {Footer} from 'https://ui-l.vercel.app/Footer@1.0.0.mjs'
import { useState } from 'react';
import App from './_app';
import CustomHeader from '@/components/CustomHeader';

export const getServerSideProps = async () => {
  const res = await fetch('https://fakestoreapi.com/products')
  const data = await res.json()
  return { props: { products: data } }
}

export default function Home({products}) {
  const [count, setCount] = useState(0)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`}>
        <CustomHeader count={count}/>
        <ProductList products={products} setCount={setCount}/>
        <div>Hosted at : https://next-ssr-lac-chi.vercel.app </div>
        <App Component={Footer} pageProps={{className: styles.footer}}/>
      </main>
    </>
  )
}
